server:
  port: 8081
spring:
  application:
    name: service-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${uv.db.host}:3306/user_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${uv.db.pw}
  cloud:
    nacos:
      server-addr: 192.168.146.128:8848 # nacos地址
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 高校联盟志愿系统用户管理接口文档
    description: "高校联盟志愿系统用户管理接口文档"
    email: 3066902089@qq.com
    concat: arima
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.univolunteer.user.controller
jwt:
  secret: Im15U3VwZXJTZWNyZXRLZXkxMjM0NTY3ODkwQUJDREVG   # base64 编码后的 32 字符串
  expire-time: 86400000  # 1天（毫秒）

feign:
  okhttp:
    enabled: true # 开启OKHttp功能
